-- Created by HTVinh 10/18/2017
-- Mon Co So Du Lieu Phan Tan
-- Quan ly Diem Sinh Vien

-- Initial Database
CREATE DATABASE QLDSV
GO
USE QLDSV
GO

-- Create Tables
--
--1	KHOA
CREATE TABLE KHOA (
	MaKh		VARCHAR(10) PRIMARY KEY,
	Ten			NVARCHAR(50) NOT NULL
);
--2	GIANG VIEN
CREATE TABLE GIANGVIEN (
	MaGV		VARCHAR(15) PRIMARY KEY,
	HoTen		NVARCHAR(100) NOT NULL,
	HocVi		NVARCHAR(50),
	HocHam		NVARCHAR(50),
	ChuyenMon	NVARCHAR(50) NOT NULL,
	MaKh		VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES KHOA(MaKh)
);

--	Them Truong khoa vao KHOA
ALTER TABLE KHOA
--ADD TruongKhoa	VARCHAR(15) NOT NULL FOREIGN KEY REFERENCES GIANGVIEN(MAGV);
ADD TruongKhoa	VARCHAR(15) FOREIGN KEY REFERENCES GIANGVIEN(MAGV);

--3	PHONG BAN
CREATE TABLE PHONGBAN (
	MaPhBan		VARCHAR(5) PRIMARY KEY,
	Ten			NVARCHAR(50) NOT NULL	
);

--4	LOP
CREATE TABLE LOP (
	MaLop		VARCHAR(15) PRIMARY KEY,
	Ten			NVARCHAR(20) NOT NULL
);

--5	CHUYEN NGANH
CREATE TABLE CHUYENNGANH (
	MaCN		VARCHAR(10) PRIMARY KEY,
	Ten			NVARCHAR(50) NOT NULL,
	MaKh		VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES KHOA(MaKh)
);

--6	MON
CREATE TABLE MON (
	MaMon		VARCHAR(10) PRIMARY KEY,
	Ten			NVARCHAR(100) NOT NULL,
	SoTLT		INT NOT NULL,
	SoTTH		INT
);

--7 NamHoc
CREATE TABLE NAMHOC (
	MaNam		INT IDENTITY(1,1) PRIMARY KEY,
	Nam			varchar(15) NOT NULL		
);

--8 LOP TC
CREATE TABLE LOPTC (
	MaLTC		VARCHAR(10) PRIMARY KEY,
	SVToiThieu	INT NOT NULL,
	MaMon		VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES MON(MaMon),
	MaGV		VARCHAR(15) NOT NULL FOREIGN KEY REFERENCES GIANGVIEN(MaGV),
	MaKh		VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES KHOA(MaKh),
	HocKy		NVARCHAR(1) NOT NULL CHECK (HocKy >=1 OR HocKy <= 3),
	MaNam		INT NOT NULL FOREIGN KEY REFERENCES NamHoc(MaNam),
	TuNgay		Date NOT NULL,
	DenNgay		Date NOT NULL,
	TrangThai	VARCHAR(5) NOT NULL CHECK (TrangThai = 'HUY' OR TrangThai = 'MO') --Huy Or Mo
);

--8.1	CT_LTC
CREATE TABLE CT_LOPTC (
	MaCT		INT IDENTITY(1,1) PRIMARY KEY,
	Buoi		NVARCHAR(10) NOT NULL CHECK (Buoi = 'SANG' OR Buoi = 'CHIEU'),
	Thu			INT NOT NULL CHECK (Thu >= 2 OR Thu <= 7),
	MaLTC		VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES LOPTC(MaLTC)
);

--9	SINH VIEN
CREATE TABLE SINHVIEN (
	MaSV		VARCHAR(15) PRIMARY KEY,
	HoTen		NVARCHAR(100) NOT NULL,
	Phai		NVARCHAR(5) NOT NULL CHECK (Phai = 'NAM' OR PHAI = 'NU'),
	DiaChi		NVARCHAR(255) NOT NULL,
	NgaySinh	DateTime NOT NULL,
	KhoaHoc		INT NOT NULL,
	MaLop		VARCHAR(15) NOT NULL FOREIGN KEY REFERENCES LOP(MaLop),
	MaCN		VARCHAR(10) FOREIGN KEY REFERENCES CHUYENNGANH(MaCN)
);

--10	NHANVIEN
CREATE TABLE NHANVIEN (
	MaNV		INT IDENTITY(1,1) PRIMARY KEY,
	Ten			NVARCHAR(100) NOT NULL,
	DiaChi		NVARCHAR(255) NOT NULL,
	MaPhBan		VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES PHONGBAN(MaPhBan)
);

--11	KE HOACH GIANG DAY
CREATE TABLE KE_HOACH_GIANG_DAY (
	MaCN		VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES CHUYENNGANH(MaCN),
	MaMon		VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES MON(MaMon),
	HK			VARCHAR(5) NOT NULL
);

--12	DANG KY MON HOC
CREATE TABLE DANG_KY_MON_HOC (
	MaSV		VARCHAR(15) NOT NULL FOREIGN KEY REFERENCES SINHVIEN(MaSV),
	MaLTC		VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES LOPTC(MaLTC),
	Diem		FLOAT CHECK (DIEM >=0 OR DIEM <= 10)
);

--13	CT_GV_MON
CREATE TABLE CT_GV_MON (
	MaGV		VARCHAR(15) NOT NULL FOREIGN KEY REFERENCES GIANGVIEN(MaGV),
	MaMon		VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES MON(MaMon)
);